swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{userId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: List all accounts
      description: API to retrieve a list of all acounts for a authenticated user
      parameters:
        - in: path
          name: userId
          type: string
          description: ID of the user
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: Accounts retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{userId}/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: List all transactions of an account
      description: API to retrieve a list of transactions for a authenticated user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: ID of the user
          required: true
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: query
          name: filter_months
          type: string
          description: Optional filter by months
      produces:
        - application/json
      responses:
        "200":
          description: Transactions operations retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{userId}/{accountId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Read a specific transaction
      description: API to view a specific transaction of authenticated user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: ID of the user
          required: true
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
      responses:
        "200":
          description: Specific transaction retrieved successfully
          schema:
            $ref: "#/definitions/Transactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{userId}/{accountId}/{transactionId}/update:
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update description of a specific transaction
      description: API to update category or note of a specific transaction of authenticated user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: userId
          type: string
          description: ID of the user
          required: true
        - in: path
          name: accountId
          type: string
          description: ID of the account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction
          required: true
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            type: object
            properties:
              note:
                type: string
                description: Updated note for the transaction
              category:
                type: string
                description: Updated category for the transaction
            required:
              - note
              - category
      produces:
        - application/json
      responses:
        "200":
          description: Description of specific transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transactions:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      userId:
        type: string
        description: ID of the user associated with the transaction
      accountId:
        type: string
        description: ID of the account associated with the transaction
      transactionId:
        type: string
        description: ID of the transaction
      date:
        type: string
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Balance after the transaction
      transactionType:
        type: string
        description: Type of the transaction
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Note of the transaction
